<?php
//file : app/config/constants.php

return [
    'RECORD_FETCHED' => 'Record Fetched Successfully',
    'RECORD_REMOVED' => 'Record Removed Successfully',
    'RECORD_ADDED' => 'Record Added Successfully',
    'RECORD_UPDATED' => 'Record Updated Successfully',
    'RECORD_NOT_FOUND' => 'Record Not Found',
    'INVALID_ARGUMENT_PASSED' => 'Invalid Argument Passed',
    'UNABLE_CHANGE_STATUS' => 'Unable to Change Status',
    'ALL_RECORDS'=>10000,
    'PAYMENT_DONE' => 'Payment successfully done',
    'PAYMENT_FAILED' => 'Payment Failure',
    'VERIFIED' => 'verification is successful',
    'REGISTERED' => 'Registered User',
    'LOGIN' => 'Login Successful',
    'UN_REGISTERED' => 'Not a Registered User',
    'OTP_GEN' => 'OTP generated',
    'OTP_NULL' => 'No Value provided in OTP',
    'OTP_INVALID' => 'Invalid OTP',
    'OTP_VERIFIED' => 'OTP verification successful',
    'REFRESH_TOKEN' => 'Refresh token is successful',
    'WRONG_CREDENTIALS' => 'Wrong credentials',
    'USER_DETAILS' => 'Authorized user details',
    'USER_UNAUTHORIZED' => 'Unauthorized user',
    'TOKEN_EXPIRED' => 'Token is Expired',
    'TOKEN_INVALID' => 'Token is Invalid',
    'TOKEN_NOTFOUND' => 'Authorization Token not found',
    'USER_LOGGEDOUT' => ' User successfully signed out',
    'SMS_DELIVERED' => 'SMS delivered successfully',
    'ORDERID_CREATED' => 'Order Id generated Successfully',
    'REFUND_INITIATED' => 'Refund Initiated',
    'REFUNDED_COMPLETED' => 'Already refunded',
    'NO_PAYMENT' => 'Not a successful payment',
    'BOOKED' => 'Seats already booked',
    'LOWER_BERTH' => 1,
    'UPPER_BERTH' => 2,
    'BOOKED_STATUS' => 1,
    'BOOKED_STATUS_FAILED' => 0,
    'BOOKED_CANCELLED' => 2,
    'PAYMENT_DONE' => 1,
    'REFUNDED' => 2,
    'NEED_GST_BILL' => 1,
];